// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_proto.proto

package user_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	FamilyName           string   `protobuf:"bytes,2,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_865da0cddf9720c0, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *RegisterRequest) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type RegisterResponse struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	UserId               int32    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ErrorCode            int32    `protobuf:"varint,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_865da0cddf9720c0, []int{1}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RegisterResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterResponse) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RegisterResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

type GetUserInfoRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoRequest) Reset()         { *m = GetUserInfoRequest{} }
func (m *GetUserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoRequest) ProtoMessage()    {}
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_865da0cddf9720c0, []int{2}
}

func (m *GetUserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoRequest.Unmarshal(m, b)
}
func (m *GetUserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetUserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoRequest.Merge(m, src)
}
func (m *GetUserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoRequest.Size(m)
}
func (m *GetUserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoRequest proto.InternalMessageInfo

func (m *GetUserInfoRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type GetUserInfoResponse struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	FamilyName           string   `protobuf:"bytes,3,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	UserId               int32    `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EmailIsValid         bool     `protobuf:"varint,6,opt,name=email_is_valid,json=emailIsValid,proto3" json:"email_is_valid,omitempty"`
	ErorrCode            int32    `protobuf:"varint,7,opt,name=erorr_code,json=erorrCode,proto3" json:"erorr_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoResponse) Reset()         { *m = GetUserInfoResponse{} }
func (m *GetUserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoResponse) ProtoMessage()    {}
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_865da0cddf9720c0, []int{3}
}

func (m *GetUserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoResponse.Unmarshal(m, b)
}
func (m *GetUserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetUserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoResponse.Merge(m, src)
}
func (m *GetUserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoResponse.Size(m)
}
func (m *GetUserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoResponse proto.InternalMessageInfo

func (m *GetUserInfoResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *GetUserInfoResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *GetUserInfoResponse) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *GetUserInfoResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetUserInfoResponse) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetUserInfoResponse) GetEmailIsValid() bool {
	if m != nil {
		return m.EmailIsValid
	}
	return false
}

func (m *GetUserInfoResponse) GetErorrCode() int32 {
	if m != nil {
		return m.ErorrCode
	}
	return 0
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "user_proto.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "user_proto.RegisterResponse")
	proto.RegisterType((*GetUserInfoRequest)(nil), "user_proto.GetUserInfoRequest")
	proto.RegisterType((*GetUserInfoResponse)(nil), "user_proto.GetUserInfoResponse")
}

func init() {
	proto.RegisterFile("user_proto.proto", fileDescriptor_865da0cddf9720c0)
}

var fileDescriptor_865da0cddf9720c0 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x4e, 0x3a, 0x31,
	0x10, 0xc7, 0x7f, 0xcb, 0xdf, 0x1f, 0x03, 0x51, 0x52, 0x35, 0x6e, 0xf0, 0x0f, 0x64, 0xe3, 0x81,
	0x13, 0x07, 0x7d, 0x04, 0x0f, 0x86, 0x98, 0x78, 0x58, 0xa3, 0x07, 0x2f, 0x4d, 0xa1, 0xb3, 0xa4,
	0x09, 0xbb, 0xc5, 0xb6, 0x4b, 0xc2, 0x8b, 0xf9, 0x36, 0xbe, 0x8b, 0xd9, 0x29, 0x04, 0x50, 0x56,
	0x2f, 0x9b, 0xed, 0xf7, 0x3b, 0xd3, 0x99, 0xf9, 0x74, 0xa0, 0x9b, 0x5b, 0x34, 0x7c, 0x61, 0xb4,
	0xd3, 0x23, 0xfa, 0x32, 0xd8, 0x2a, 0xd1, 0x0c, 0x8e, 0x63, 0x9c, 0x29, 0xeb, 0xd0, 0xc4, 0xf8,
	0x9e, 0xa3, 0x75, 0xec, 0x0a, 0x20, 0x51, 0xc6, 0x3a, 0x9e, 0x89, 0x14, 0xc3, 0x60, 0x10, 0x0c,
	0x5b, 0x71, 0x8b, 0x94, 0x27, 0x91, 0x22, 0xeb, 0x43, 0x3b, 0x11, 0xa9, 0x9a, 0xaf, 0xbc, 0x5f,
	0x21, 0x1f, 0xbc, 0x44, 0x01, 0xa7, 0x50, 0xc7, 0x54, 0xa8, 0x79, 0x58, 0x25, 0xcb, 0x1f, 0x22,
	0x07, 0xdd, 0x6d, 0x21, 0xbb, 0xd0, 0x99, 0x45, 0xc6, 0xa0, 0x96, 0xe7, 0x4a, 0xae, 0x6b, 0xd0,
	0xff, 0x36, 0xbb, 0xb2, 0x93, 0xcd, 0xce, 0xa1, 0x49, 0x4d, 0x2b, 0x49, 0xb7, 0xd6, 0xe3, 0x46,
	0x71, 0x1c, 0xcb, 0xa2, 0x59, 0x34, 0x46, 0x1b, 0x3e, 0xd5, 0x12, 0xc3, 0x1a, 0x79, 0x2d, 0x52,
	0xee, 0xb5, 0xc4, 0x68, 0x08, 0xec, 0x01, 0xdd, 0x4b, 0x11, 0x9b, 0x25, 0x7a, 0x33, 0xe1, 0x81,
	0xba, 0xd1, 0x67, 0x00, 0x27, 0x7b, 0xa1, 0xbf, 0xf4, 0xb8, 0x4f, 0xa8, 0xf2, 0x07, 0xa1, 0x6a,
	0x39, 0xa1, 0x5a, 0xc9, 0x8c, 0xf5, 0xbd, 0x19, 0x6f, 0xe0, 0x88, 0x22, 0xb8, 0xb2, 0x7c, 0x29,
	0xe6, 0x4a, 0x86, 0x8d, 0x41, 0x30, 0xfc, 0x1f, 0x77, 0x48, 0x1d, 0xdb, 0xd7, 0x42, 0xf3, 0x24,
	0xb4, 0x59, 0x93, 0x68, 0x6e, 0x48, 0x68, 0x43, 0x24, 0x6e, 0x3f, 0x02, 0x68, 0x17, 0xc3, 0x3d,
	0xa3, 0x59, 0xaa, 0x29, 0xb2, 0x47, 0xe8, 0x98, 0xf5, 0x7b, 0x70, 0xb1, 0x50, 0xec, 0x62, 0xb4,
	0xb3, 0x27, 0xdf, 0x56, 0xa2, 0x77, 0x79, 0xd8, 0xf4, 0x88, 0xa2, 0x7f, 0xec, 0x0d, 0xce, 0x66,
	0xe8, 0xb8, 0x6f, 0x3f, 0x4b, 0x34, 0x9f, 0xac, 0x38, 0x91, 0xba, 0xde, 0x4d, 0xfc, 0xf9, 0x12,
	0xbd, 0x7e, 0xa9, 0xbf, 0xb9, 0x7b, 0xd2, 0x20, 0xf3, 0xee, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x2a,
	0xbd, 0xf0, 0x60, 0xc8, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	RegisterApi(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	GetUserInfoByUuid(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) RegisterApi(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/user_proto.UserService/register_api", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserInfoByUuid(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	out := new(GetUserInfoResponse)
	err := c.cc.Invoke(ctx, "/user_proto.UserService/get_user_info_by_uuid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	RegisterApi(context.Context, *RegisterRequest) (*RegisterResponse, error)
	GetUserInfoByUuid(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) RegisterApi(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterApi not implemented")
}
func (*UnimplementedUserServiceServer) GetUserInfoByUuid(ctx context.Context, req *GetUserInfoRequest) (*GetUserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfoByUuid not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_RegisterApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RegisterApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_proto.UserService/RegisterApi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RegisterApi(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserInfoByUuid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserInfoByUuid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_proto.UserService/GetUserInfoByUuid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserInfoByUuid(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user_proto.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "register_api",
			Handler:    _UserService_RegisterApi_Handler,
		},
		{
			MethodName: "get_user_info_by_uuid",
			Handler:    _UserService_GetUserInfoByUuid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_proto.proto",
}
